apiVersion: v1
data:
    username: ENC[AES256_GCM,data:VR3iO5WhMeRlU5zN5u8=,iv:+xD2qyDFqnYlddoac8Bx0PUxConyCLlfSP272QZfR7k=,tag:NQvGsInbGHSlIc/ae0XPlg==,type:str]
    address: ENC[AES256_GCM,data:m21WE19XkmKL0RfujETL4Sf/tkBwj0q5/EO93wz+cIIZ2LvattNAS7pNSW1ly6pg71vDAxua+GljD6fyr3xYJuhKklzJWagqAlqANAhEraTl+0iVp/feu0WxOVLsf2dmQxanXhQd4XetYW3i2jD6b7Ku+R5SrfdJ,iv:6+HOnpNDFzd5V4kAxDEJ++NOIwKH1RPNovof5puD1Xc=,tag:/69+/cjaNfDLYgcbdVShaw==,type:str]
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-22T20:34:15Z"
    mac: ENC[AES256_GCM,data:sN1jE+FqnZiE/KdteehFjmrNIp8BRJLe8rt/7Us7fg8nNpZZ5af5n+5RmCvnbJMSfncfErBpwn5iCoHaYlIWrZx+1FoQflxljnJbCxY5dvwIUdi/1bB/aO6cYR4D/fYS8bvbaN3XoWg3s+50kq/062rbXhzi+Si7DlmLSGV67aQ=,iv:70nTRUlcMfjKRQ2lh6a1/G2nAfSP6zKQmY9rRuA8JVE=,tag:vTIntEQpFzx0MRKYfQnH6g==,type:str]
    pgp:
        - created_at: "2021-08-22T20:34:15Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA7o1G9YUCENaAQ/+Iop0cjJ5dBtlwzg0TRO/zHCqiquRTXSmcWRHvc/atZTO\r\nqp1Z6ABt2Trvgn/BTMC1e4+cERZLyoLJ1NI042u4FPzWI1kYPYUAyh+LVtsbZb+U\r\nPhq5oE6uuYilStnfh7Z+z5ozu9Zl0JiXoOHZ75+Z9RAwHXsn+3YIoU7dxSV6YaSJ\r\nz6lycqALFORU0nGCKPmDq+KhMEYXhowEVycoRkIATJytiIBlbGw0N3DhqT30Tm1N\r\n//U0hgwd8icCT/OC5I6c8CqKI6j1cYfHsWMBzfXsilcAyXCGbMoIYwrvcZvzUIXZ\r\n1MeHTN0igRBAhUjP4hXJRq5va9SLPoFxBmyn7a80j0FEXmTG3diEhsgsQsopdmao\r\nvxmYEwZyPnXIMfm53u5A5SqZG1pb1yDm9IWf5ysOh7fwaVDodbDmLK4NlFNcI4km\r\nZbGvi8V3JIZ1uXECgFyGwHzOSM/AutcCYBgIuCZl/9DGZenT2k5zn5c5jndRFPsB\r\nUUUwswOhQhX4HTuYlfy1qf/keVb7D5OLZmuxbLnaPAArPEyeytnOFA5SDOjgXOUF\r\nZZ6/vOJidPOXwWxbMCKSwV52+orHQNCCDSzHp7u1bOr9CWu2RxQqIkQiMG+TvSqR\r\nBkbB0/jo5zAn995wNcfA6n/nUmEFxMqs23mnz/NAKHTNyrly9vY/KDLAavTS8JrU\r\naAEJAhWki0031yaHDAaXlNE0bzUot4EfO8Y/Zv+bW83YKpCbXxrtEBfy6oT6uvKx\r\nklqSvxOvvVRsUQHI8xsXIPSTKH2E6Ctc/rmtBKzZmdeByYldAWLRGxrM7aNZSUiP\r\nHsQgKC2BCK1J\r\n=Jh8V\r\n-----END PGP MESSAGE-----\r\n"
          fp: C9E9F89A87602182D106AF2C1FEEAA0B0634069C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
