---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
  namespace: auth
spec:
  containers:
  - name: iscsipd-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: fermion-block
  volumes:
  - name: fermion-block
    iscsi:
      targetPortal: ${ISCSI_TARGET}
      iqn: ${ISCSI_IQN}
      lun: 0
      readOnly: false
      chapAuthDiscovery: true
      chapAuthSession: true
      secretRef:
         name: chap-secret