# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    BASE_DOMAIN: ENC[AES256_GCM,data:Gn3hLUM3gAKWYtNVEA==,iv:qj08smJ53jRfoPlKDVNKGp+TsgIITh7A24Oe9PDU87Q=,tag:rGppz9BBQYcGDfNVyq/F3A==,type:str]
    BLOOPNET_URI: ENC[AES256_GCM,data:EkLWSqwYmdUw7wy/Lc/l,iv:T19kIEYK1dy+hNA2erFqCkk8SV4j4Y0QJyreC/nzN3I=,tag:T1EFx5rL4oWtbUD8za+2yg==,type:str]
    SECRET_LEPTON_IP: ENC[AES256_GCM,data:/+vPz6yZZ5ms/3stDjk=,iv:h7aIXaVNmHLPfVe0BeFlEeCYmlnwPTP/9id8IDd9Ilk=,tag:hachezGDxb809x1+ta81iA==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:9nmdBa0wrp0IuFf/q0Pt5KRQQN5bYS8rSxBgNLo5dG/dC0Y78LuiBg==,iv:ePohFRfaIQDn4iOBl5Nq+69uV3lNiYhI4RvNHjisIb4=,tag:t8+VkiZhngYZRbDMLctt3A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:phc7ybHQg38LwWvrWsc0IspXR+o=,iv:hDP7GnaFxwwfH21z9mvo6mae6Z2uhLlWXJKA40RRUaM=,tag:SPjEcPzON3zhB69NOJelLA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mDPhqhbEHt+KbgUsG2wKDutv,iv:2Yg0oTW2aPmxLbhR0/cRKQutm+2Jnc3/4HGeyt55VDA=,tag:PiWYEGhtXFbgDTYMrR2+8A==,type:str]
    SECRET_TRAEFIK_PILOT_TOKEN: ENC[AES256_GCM,data:iCBsqglrwNdmwNM=,iv:cm7qsyKq1GKz72UEoPO2vmQyhjRD9JLJDyPrFxvb/H4=,tag:Cxz5laSN51vV9K/idOerbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-28T17:09:47Z"
    mac: ENC[AES256_GCM,data:yz34C1eigwCP6RfG9HcTQfCzUG0A0DNdwS2g9k/kvITTub/qfRmuSUC+oGBnA8BY+x+s0KQmRmyHwYTMPbn2jxU1++i9hfmvym6MG7ThWzxeSolLh/fIgCtU//XcYM9FbP3jZSL1TxSk/I58snrc2Le3l44MCfQq3uljAsa0E1g=,iv:JCuUxTrVNKsZdH3ceqGK7AzZV+L5ZOrAzg780nC+oVU=,tag:AoZCtW+6MHJ37YMPPohBlw==,type:str]
    pgp:
        - created_at: "2021-08-28T17:09:46Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA7o1G9YUCENaAQ/+IlKdBC5c5z0+pkvd9og2+PoA2GJGgrNzuC5AMf073N8k\r\n4XPW9aQj7v2iVoxE/V383e/3YrtJkDX1oPX/Pq4RABCtIU/5scbKGL2kkv6ARpqy\r\nmcoeWMqcnaMODU5S0v87c+mYQrqkyI1jCG8xB0NvaXHcERpWiH/cPBx9JL64Sklg\r\n8UO3PHOeTWbh99kjvsb+VqPQbezBdYxa7ocUMgFpSYlwgrX9/uMEEtNBhTIC8UWL\r\nx8zlfAteusoI+uhRtHl+sL9E7jE5V0oCAtUsMy3V3e5IK7pP2xCVzWC6TbmfvPqp\r\nZaSZXEHQq3IQm+GGCvi+lBvIEsq3fWod61ApF/q94bJ8/IEa2m3VbE2hCja+q+xI\r\nDMa4X4349yy1nel97lB0Z26eCxSFujARjOLeTkI7if5l+qEi8f7uTfzfLxqnfGfY\r\ngRqRwMRNwnk1IC6wqkGPPW+AnYPh0hBHgFdRVP3drqhnANhMasuG7SVb/2E5uVid\r\n5isU2VG+zzQk9v9dTgxFBwDFWpulLDsVj0KJvfIxz1WjvW8YfncqyeXDcD/JLOPB\r\n57Gu+dTCsfYiq+pFiSYAFY3gdz4ycrNICkw/4WkZcS3jjeBEyGKPnp6Ot97oCzCB\r\nXObxphIncC8+fY6v18NoJCFGgw8Q0A+CIbfQ8N1z/iRA0Ba+MZIcWqhilNpSs+DS\r\nXgG3ZWViX9cFlJnGLx+BRVOLMzL9feH0fkWnMDNXPBFZlBsS+Yigv3AITFxnx14D\r\n/Xb+p/ujDt9m8QiUVaF2kyT8a9XgAmeb42dt4JzwAZkN3RjB62/57hUzRQWaGxU=\r\n=RW8n\r\n-----END PGP MESSAGE-----\r\n"
          fp: C9E9F89A87602182D106AF2C1FEEAA0B0634069C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
