# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    BASE_DOMAIN: ENC[AES256_GCM,data:Z5vzNFrW8UivY9BoNw==,iv:aNwR9Mrbz8cf/5M9a0aI3/ZmVDjLfAmrz+ykEy8Pklg=,tag:Kp9LA7969bpE8lH7LVz//g==,type:str]
    BLOOPNET_URI: ENC[AES256_GCM,data:RLRB26+qkBjHtwsQyhPN,iv:4ceTxFs02Lb9olIPQuxgAW/jIiX51HIpFGhO0b6hsQg=,tag:mTfbNvXSZT0OUgl17UYDAQ==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:qrF39JVqQRlCoX0FkJ1KK3UjqUUF5oRgDdGdHct/e+zlUMoquWgIgw==,iv:Rw8jIwbz6zJB3iSOBcdMOHc1o3sjPqF2hlWoOPpv7bI=,tag:GlYC+tNZhHSO/+B44EYmqw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:d7LO0OQuv/kaOzWBMqfS4Kik9pQ=,iv:9Wun74t75trmy4HRy9+FLpiwTSlkPdbhzLkgSU9vujQ=,tag:tfPtlmB+tHkSrwOEsT5BTg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qiR5ud45jAisXDV9FyemTFTo,iv:1pSgquEF/2rgH0LC3zp+KNp9LWbK07cfp7hI8f14rUw=,tag:a1+n2UyAsCTt+CN0VlOj/w==,type:str]
    SECRET_TRAEFIK_PILOT_TOKEN: null
    SVC_TRAEFIK_LB: ENC[AES256_GCM,data:oYXE949pzugbXPaq1X0=,iv:7471igYY9Xhhd7KF81jcqLdkSVi9fwh7okZXtppQtjM=,tag:1s1VgmRZCg3xr/ij9l3Fhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-26T00:13:25Z"
    mac: ENC[AES256_GCM,data:Tx2tQklX0BNkX9/9HA/ugsoWXDipY/FpButhZuMd+j/XbcFLU/5xBeP1TdT55FkNQsKhTWJaOGSZa8QUBVp4LIbYUIj/dSZ8iT8GG4tSJNRFYfjLOB9s9DBqItzZ2r5dOWdQPlj+KLdzr+krYCrXg6F1vSakJg1HhOZEZLPZqIs=,iv:WAsWnOhxoLIBY4VWdSNk+7tPaAjudLVtSvK7r5kQE80=,tag:ACo/L7+LqfU1MzY027ZMLw==,type:str]
    pgp:
        - created_at: "2021-08-26T00:13:24Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA7o1G9YUCENaAQ//WJ/ft6GG8R0GCmTCaAmeCvb+qJOZq8R2RCPdiXpfeEyw\r\n/vXUYs0a3A3GsAfeijEhQcX6JKgPrvFnKdjeyCIzX002f+1yRmZgaJNYtzGhIHWx\r\niy+m6snaOIBBZ7/VkAx79PnlL9lf91MJULZ25c04+G6SapselwQ7OW+pWM4rlGUm\r\nHcMELcmd+npgd7oIn3tADK+Ff+6cFJaInF1Di2fjgAjFZhUxgRWbFkOOEQmSSZ6z\r\nuTuZHDTAHPcCX4of2z+IgwvmQXXUp2HBQrKcrfy+cHhoks2NuzXCm8ijOCRdH8i/\r\niLmzEsAt+XO6aXYhF8cKiTtuldgmPA0P4ZeTDmE+sZjnJ1pRpNl6oE/JyaUn1kpm\r\ndA0bo+z3kZBuw8KYB6nbzzrEVeCxJU9rrEOVRrYclPL2sB/8NGbaxUN7taLEAjFz\r\nT5ahWOh6R0tsDj0eNTkxWioE8mzJtr4rJDQJ6x7XqLVi37B4N+le38p2N1WyQrgz\r\ny5LgMJofsSbE9o6LBG5DzH3K8ebfVR3f5V6Y6UrtZoFlTYcNtRLWUhtgLgCLvs36\r\n3kjWK9jPTLYrRVxUmZntKWc1mkO8WIruDnmn9U3dQkEhorhfN4yu3i9v5AB90TBZ\r\nh0yxePP+u5+pCLfv8LpGSemmAEK4QCNkOUy063lpOtKr1TMqzs+y7lxO2ril/KrU\r\naAEJAhWvj5S/49PTtkPkN+uDUIPGlAPIBSLDVs+LgAByXHPhlZ68PjJwiBQG8aDh\r\nL39d+OHQank7hdQLXNUTFt/v72wsHj4mGhlNrKgr+IqlPPve1xl53aQXY0eZ0AD6\r\nfqHkufRBYEpT\r\n=mycb\r\n-----END PGP MESSAGE-----\r\n"
          fp: C9E9F89A87602182D106AF2C1FEEAA0B0634069C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
