# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    BASE_DOMAIN: ENC[AES256_GCM,data:pg1H3tfwGzUuPTXtaw==,iv:X1hu1XArfF9LefCyT2j06vKdPxJUUIvb/2dsMvOTaXQ=,tag:C5PadydHU80PVP3JV1QhuQ==,type:str]
    BLOOPNET_URI: ENC[AES256_GCM,data:/lWRS0u7nt64Yd8mnjr0,iv:GJGc5ia0GRY77WWqiPsrxewlxDhfZ63oPm0r3TJ6Ddw=,tag:h0jrXKGHH0Tx1W1HpMWs9A==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:u+mflU/WGfmbGMaKsAGtHeD+wOuTJp+W/cEv2XGv6a+F0vcyKSwfvw==,iv:Hne7EiD5KTDGNtB/SvHk6Lp1HvT0haQebWYx6/8TvEQ=,tag:pGQsfdG+rI9JKC36Tv/9lw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:esAN9MFQAgOcoPRFIsxkfGoYqkk=,iv:YULcfdh+n3FX29f3CBIVBIlOkBO+P+fCuMA8lqQtkL8=,tag:bN5RWciG5cpj94rD0Up+6Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:TGllDIRIsP20HZP7JW1krFM/,iv:oTFDnUH1zKlIM9S6t2+/LAmM/TVYIlBSuZdUvR2UUZE=,tag:KttQxi3aW/Y+DYDsdpptjA==,type:str]
    SECRET_TRAEFIK_PILOT_TOKEN: ENC[AES256_GCM,data:ALuUG5ZgGJ7FcNM=,iv:Vetqq847fps3rp3z+/rCoDWgGPz5g+gY3lISd3L7apU=,tag:gYgt8q4J5HLYz9pRLFubFA==,type:str]
    SVC_TRAEFIK_LB: ENC[AES256_GCM,data:AbWFykV/+dBe5wjFJ5s=,iv:JUcnUnf/Vkk0pGMcWYXY/waWf34edg82uoDfUYpd+RM=,tag:EI4lUrUuR6BAOGFU2WmPwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-27T05:58:04Z"
    mac: ENC[AES256_GCM,data:xu+8viGKDQUm1ZKvSkb61GpZx/K5NjhuNHGpkbnPUk6TfPMJFzlaREW0p7RekHS461xXeARB54MNg8qwiuzUsr/gFaAzymIA6CYqGhrohccGXAdYTQf2YwRjAC1ly3eOti/ltXyNpaz6848D02lvehZgeBhMYs3DBa+rKOBfE+g=,iv:YsAdfCkTNPoYKtyqPjUhsP2NtAh7J9ssbMicpThguBk=,tag:rWibGl/H4JoLtDKxvcAfGw==,type:str]
    pgp:
        - created_at: "2021-08-27T05:58:03Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA7o1G9YUCENaAQ//cNa1k26zWci5FMIzYcMBhHehsly71/szCMX5lEcZ2mEu\r\nRaAl9/C63YG/tt+08Jkhzti4egkNjeNtiIWc7dcxH+zlV2BaGBEQy6Pvvi2hVqLn\r\nfYUGzAQ9W+aWAgOAFgxFIdiii3I1BRH2By2ii+e/Q5aS2IKQH7RYqntN9hi2Ojcm\r\nzi4z2nBv1OhYNCdKJfM/wGWSKs8O0iM1XtOkTowaWf7WiaHItsqK3xE3QBmJvekt\r\n3vpUns/en4iCgyTmNF0HnMjPBdejYWUC3tbfKP82F39oh7jODW5ShIiJulVIFmn5\r\nNoUqycXukTDUinlJ6Z88eHAkxE3lot/vGkvA2c9SxjMumRfohpnCuZfNduj9hJvD\r\ndpcaAJo3SiV2ZqjxdB7sCXBOn2b1/Fj4mW17aSjjkPWuLR9zQn/BTDHIyea0ue83\r\nNjzwk4c6vIfiIlylfg6jc5n6FqkWu1EonbCeJO8P2SPyMeze0KF+JxVie8hllajK\r\ncgHGetkKSm8Gx0Z4gIehfu61mI3a6mTbyKg7iaIQxKMEef7b9XE1Vpe2xmb3wt4p\r\nVwqH/XVZqzu6lluz0kyWCH04vF/E4enfegWmrbH0O97Knpph68atMp84aWfvlQ5d\r\nl9VDtsLHTX+s9BJ28a+sPUlJccqTdiFY8J5N3Yu4oTwJ0TXr2vOfhgBemzd5BR7U\r\naAEJAhUPAmtEwHQLEcW1RgFU8pwGurg8NnAHnttDiyRUeUggaphjOT+co2ANhSk/\r\naTcKiPINxluwEtvefyYherwTiJJ6eFDcYR5dunhPexXCFBKJ2vEMfoKJZ+obvSiL\r\n9kX7iTEZ8GV3\r\n=KtY/\r\n-----END PGP MESSAGE-----\r\n"
          fp: C9E9F89A87602182D106AF2C1FEEAA0B0634069C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
