# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: basic-auth
    namespace: networking
stringData:
    users: ENC[AES256_GCM,data:/m9uiDUP4igGLc9rCFJ72M1yFEhf+KFjmhdJgrbYRnJVDRmEuqgX,iv:pPEZdW9xxzGXKdBhAkVgLXYY6iD9gJ/RlixRTgRpS4o=,tag:X3s1lzRbAwzr0dkYF8DYXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-26T00:09:07Z"
    mac: ENC[AES256_GCM,data:CqRk9gKgQZ3pAPS72lxFYziumKPjwmBuTp74JFtTjefZus9fGJua7CxXgBNWzN/HgucW2klqFamOgBzlYaQXken322Re4GNjrfd1qoem6U1cALuFcv17q5hhaTCydNSIiwHgNMoRBy7EWLP/puAZxwRoO6iIa3uqRb630TnMbpw=,iv:JchnjrHJpCfbNDDRLmqiGjVx2FoyxE1vsyyBN9NYneg=,tag:BozbHppSKqeDydeo7c4PeA==,type:str]
    pgp:
        - created_at: "2021-08-26T00:09:07Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA7o1G9YUCENaAQ/9H8lEqf31LBQHYzUY8qhvOAT3QpnZ+Sk1OS9ngWxuZMpH\r\nhotK41UBus8ezq9z2tuysBAyEteg4o2hxm/+4el/jxh9g9hHtFtNLfUB65EVB3/a\r\nREi3uGNUxttCL9PwTa0n2acQPABMVM6yV7yT9j0yRv7fxhjyyKojGex75o2/lx3y\r\nJEu3fYtEKAB4QaIucH6gheX7OzWqvzPJFZMP7i6lXcTnv9QErV8wrlBh/MbnRM8+\r\nDTsm7wREtWe1cKOpJ9d4tFs6lgUT4YaM7mvBXT1pVpEGHADQNaeb/PLU+FIBVp5O\r\nBwzysopGWQ8n68Wkhcr96t0JUJfB79XNcTVZ9q0Uek2q7XAG8Eeta+ijAFktSxI5\r\nmC8fcKp85/Mby0FU/eDmURoZqneIW6/Xprf6Hl4nP7H7UuQafqBcF7eAS1CyXB+Q\r\nh7ICqNCCr7O8/U67suD1YP13xTNS0XsZZeZhutxuxEhACfBgh5vzGCHQ4UwuMijP\r\n6NhcDCGc8SJ6QKDrZKlohmIB5vUGIyHRs8vTuGiY+xUIIQmPBiSH13wPsLzFLfdV\r\ntneFXxm1k9rwcWcJijsBr2eg1FlsshNX38PqCODenKBwwsKNbYDqmJ/eEQGv027U\r\naM0YPCyu0fqZUnh/PSr9PLO5t0v4+blSmLSD6lYeTgIwbjf/EmJgHiP1oEZrD0DU\r\naAEJAhVWYNYrinmIrqq7X97jxHSn1AHcpwsZgObiL38eyN0tfQwwkilStV0kMQfW\r\nwVVynm/17sJ1IqSXkVt2rB1YT6cZeYVolUt9h7DjQCzraf2Bf4TIDC6/c/+tzqgm\r\nXPbjnhSL0AI8\r\n=ZawB\r\n-----END PGP MESSAGE-----\r\n"
          fp: C9E9F89A87602182D106AF2C1FEEAA0B0634069C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
