# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:LNHse21cansozOdfWCbYBT1ZF6ctWLK2FxTqO7x9vCyA1Fnp2OIvpA==,iv:bnzcnBJy1gjBbs5FStsGtTaGzzOhtgTv3XZpDf9li/Q=,tag:816hqyuE3w1HrfZfX4eqOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-29T00:03:43Z"
    mac: ENC[AES256_GCM,data:nKKNKD2qMv7G9G4A5EaoDeOM3mmqJzLcmia9v8v01O9qjm1NjjsBWxYg3MmwwGnGv83UZXoFTZMY+V/8pPRQyJXPh/eN6qv5XwNq9W0hRgsVab+EoqoyONLezumd+hWLbDDrNgXwF8GSiwtdO9aMU9J3xm1ruFoPC1PZEngxm0s=,iv:wYRMqGJmi7SXaR1wQpv4wn1zJVoqVtP9DWy+3DVlnOg=,tag:ezLjLAx7dTVgevKoh9qWpw==,type:str]
    pgp:
        - created_at: "2021-08-29T00:03:41Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA7o1G9YUCENaAQ//TfgKuJv1HvPItObZ0vASXybNkLoMenOtAL3GF8bt3ooZ\r\nnTEzW62mhRJ8XxkkbWxVV+gNW9VRQVWzQFx6ey5h9rVV8f6suT0dCI8J/dDDUCIx\r\nbNC3ak0MhPsysC2R6CivaJbzbC96kgkznOjBY3zpmXhJ8I8D6Sbyg+lEZoGUDeuV\r\nZV1TH8JXj+cEs/Z5PjoCVaa6bx+T3NNDVSUhQdPJgwPQVITrCDkzaZwgZaOpXg/I\r\nyrbPskFcqEEdtg/0juNJOe/GSfvdNzkAlNa/h0Qbp0vgYD4NTar6g79br5CtFzXs\r\nej4X3zwu64rLfNb1Fl5EDllLzrPiwFkpaGGvBeO7mQkTy2xXwGWgG5JBrjt5Vyt5\r\nAi1+ruVNXV24uyc7Tw4gJ39uj1iaH6fJXkXpucw16FCCxFt/60vsgNvsUUDbaqyx\r\n+2Pb+rRbNENQM4khijVVSoo7IdAqBiOrHAovH2yKVj5kVXnnwXFO+18MJhXpPH2N\r\nMiDiQwp3v4IqqxS7CbTITk/LyA715WRF28mKI7iLKVLWMAD4d8x+EAqVf+EWQBHW\r\nkOu+UVRqd1azNHtxju44ksV/KxY/PNW9gxHrFbA5e90+KRJH2ja4wJkwsAVnRG1u\r\nrQThFsSeLUWtD+r5yJlrAx6+26BxhSBs3SSuohI3NB/kLEgpbYiLf0uuMGyy19XS\r\nXgHG1642ns6vJiTprEfYii+V8Gl2VQ0KCFMsy7bnsfrSaT+8bkWo+XEeZSrOXkgd\r\nEH4NhcCwYtoJLgspdgBnzwAgO6xgldBeZ8ZXb7lXwvy4wl0fl5AJOKyrNIR6x7U=\r\n=GO82\r\n-----END PGP MESSAGE-----\r\n"
          fp: C9E9F89A87602182D106AF2C1FEEAA0B0634069C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
