# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:6RramdZDgUMAgXsBv+r3a8Ia4V4TEjEhSgg1UQGoDBvtWC7G1HWBqg==,iv:S8ZIlZqImhM1sXJraGxid57Mc0hq5GTlrcIL/+75oEg=,tag:Mq6g1od4dFey05wEc4M8Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-28T20:01:26Z"
    mac: ENC[AES256_GCM,data:QMCZOv7fRqcsI1S6MhVrddoJilmlxMhvwRgogFdtSSHwRB7OTst4216ngmz4ln1MYBoM9NX7UmQWEnuNNS8VbfNzZC6y9HD2RFTHf/3nNpKMQI76qd0s98k6KRXom89Gj72CpnNMTsyTi69TNp/87TcFyBRRKAZvCVOL3uxToNc=,iv:FSzXh3OPeUK8J8bAzXMvwWvhWaYRldXhQaqpptokOFc=,tag:oim+Rdj2EEShsrNkezIQVw==,type:str]
    pgp:
        - created_at: "2021-08-28T20:01:25Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA7o1G9YUCENaAQ//SgHgiUbAnMj9/eUbbnR3GmJ4LGWQ4I9bB6+6DRF7o49C\r\n2PHjGA2vii6+W0slGg53VgzYhFqc/57PoJLeSUp+jMsX0kS6nUySz5OFXzWj1Zbt\r\nXdmqKebTOIfWVpuRmEeREw1pjQWIn5I8WGeX/iUUO21ehgnJJUmLYpkm7uiMatZh\r\ne2HORwlb1ViYFy8VWPOi5hQsj1pc2RX1R/8vtCVFvEnqX6Eym/+jZsjF8j8jIAl0\r\nOFssXpj1GivFueMDbHQbQC3n7Pp1UQ1cPfhjfKEc/LrHY2A14Y+8leAs8XncE3hi\r\nirlTiysFg4L6T69HDqBCiXx32Wpvn0Xwup2JzvAReGN9dRAPnJHVDSM4jOVMCjOH\r\nVSlX287iX6A73OG3MG6Pb3aj7kVJ3IbHC0WzbHwQDGfDv1wX6zgAxKkAIC9g+eea\r\nVuxUtinSMpD2gCLPJqUsK1Xso5i8XoonSLA1sj6GubhF08hAcRW9f3TSDhEaafo8\r\nciymy0ks97y3ZnHVLIO7EYsgRB6nsllhDE5CmHqdX8WK+hovbuSE/ToV7A1pn+CB\r\ntobMitX2l7Ulc8ywtsyd2kK/gtJdUsWFTiNe0qMSS3KaB9Tb7ux1lQ62JFMYI+3t\r\nmyENe6b0Gycg5c3KyekOspE0/DBJqBGLKJdAzFsRY2lMKzNkYiH+8WDbumqvUD3S\r\nXAHl/9sMIcoN0eUTfXPVzkAwX5rPDPRybQc1/8WWlnIzZiL4S/Ctd7USxJOqEgQ7\r\nWKKtRjlN6WrEzcHOAulnozgpSV8VXwRB1rHh+1YoBOwJ9EAcGFe2Ik00FDAA\r\n=cHSQ\r\n-----END PGP MESSAGE-----\r\n"
          fp: C9E9F89A87602182D106AF2C1FEEAA0B0634069C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
