---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 128Mi
      